# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install -r requirements-connector-radical.txt
    - name: Lint with flake8
      run: |
        make typecheck
        make stylecheck

  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test with pytest
      uses: addnab/docker-run-action@v3
      with:
        image: fluxrm/flux-core:focal
        options: -v ${{ github.workspace }}:/workspace -u root
        run: |
          cd /workspace
          echo "Running in ${PWD}"
          sudo apt update
          sudo apt install -y openssh-server openssh-client
          mkdir -p "$HOME/.ssh"
          chmod 0755 "$HOME"
          chmod 0700 "$HOME/.ssh"
          ssh-keygen -t rsa -q -f "$HOME/.ssh/id_rsa" -N ""
          cat "$HOME/.ssh/id_rsa.pub" >> "$HOME/.ssh/authorized_keys"
          chmod 600 "$HOME/.ssh/authorized_keys"
          ls -la /etc/init.d/
          sudo /etc/init.d/ssh start
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install -r requirements-connector-radical.txt
          make launcher-scripts
          make install
          PYTHONPATH=$(flux env | grep PYTHONPATH | sed -E 's/.*PYTHONPATH="(.*)"/\1/') make tests
